services:
  service1:
    build: ./service1
    ports:
      - 8081:8080
    develop:
      watch:
        - path: ./service1
          action: sync
          target: /service1/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  service2:
    build: ./service2
    ports:
      - 8082:8080
    develop:
      watch:
        - path: ./service2/requirements.txt
          action: rebuild
        - path: ./service2
          action: sync
          target: /service2/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s