apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: service1
    spec:
      containers:
        - env:
            - name: START_PERIOD_CHECK
              value: "5"
          image: josip12/docker-test-service1:0.0.13
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/_/health
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: service1
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
