apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: service2
  name: service2
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: service2
