apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: service2
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: service2
    spec:
      containers:
        - image: josip12/docker-test-service2:0.0.8
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/_/health
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          name: service2
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
