name: Build and Push Docker Image Service 2

on:
  push:
    branches:
      - main
    paths:
      - 'service2/**'
      - '.github/workflows/build2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract current version from package.json
        id: get-version
        run: |
          version=$(node -p "require('./service2/package.json').version.replace('-snapshot', '')")
          echo "VERSION2=$version" >> $GITHUB_ENV  

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-service2:${{ env.VERSION2 }} -f ./service2/Dockerfile ./service2
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-service2:${{ env.VERSION2 }}

      - name: Create GitHub Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            git tag "service2-v${{ env.VERSION2 }}"
            git push origin --tags
          fi

  bump-version:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set next snapshot version
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            version=$(node -p "require('./service2/version.json').version.replace('-snapshot', '')")
            IFS='.' read -r major minor patch <<< "$version"
            next_patch=$((patch+1))
            new_version="${major}.${minor}.${next_patch}-snapshot"
            jq ".version = \"$new_version\"" ./service2/version.json > tmp.$$.json && mv tmp.$$.json ./service2/version.json
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add ./service2/version.json
            git commit -m "chore: bump service2 version to ${new_version} [skip ci]"
            git push origin main
          fi